### ISSUE TITLE
MACRO {mar} verursacht Fehler

### ISSUE THREAD

**Issue by moewew** [CarlOrff/apalike-german#1]
Das folgende Beispiel verursacht bei mir (MikTeX 2.9/BibTeX 0.99d) im BibTeX-Durchlauf den Fehler
```
This is BibTeX, Version 0.99d (MiKTeX 2.9.6350 64-bit)
The top-level auxiliary file: jhghjghjasghjsgs.aux
The style file: apalike-german.bst
"}" is missing in command: macro---line 767 of file apalike-german.bst
 : macro {mar} {"M\"
 :                  {a}rz"}
Database file #1: jhghjghjasghjsgs.bib
Warning--empty publisher in elk
(There was 1 error message)
```

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[ngerman]{babel} 
\usepackage{natbib}         
\usepackage[T1]{fontenc}    

\begin{filecontents}{\jobname.bib}
@book{elk,
  author = {Elk, Anne},
  year   = {1980},
  title  = {Towards a Unified Theory on Brontosauruses},
}
\end{filecontents}

\begin{document}
\citep{elk}

\bibliography{\jobname}
\bibliographystyle{apalike-german}
\end{document}
```

Das Problem scheint mir die Zeile
```
MACRO {mar} {"M\"{a}rz"}
```
zu sein. Andere deutsche Stile haben dort `MACRO{mar}{"M\^^b{a}rz"}`, siehe auch Q36 in http://mirrors.ctan.org/biblio/bibtex/contrib/doc/btxFAQ.pdf

Via https://tex.stackexchange.com/q/382865/35864

**Comment by moewew** [comment]
Ist hier noch mit einem Update zu rechnen? Der Stil scheint mir nicht gänzlich ungenutzt (er ist mir jetzt schon zwei mal in recht kurzer Folge bei goLaTeX über den Weg gelaufen) und es wäre sehr angenehm, wenn die `.bst`-Datei selbst keine Fehler produzierte.

**Comment by CarlOrff** [comment]
Ich habe das völlig übersehen, weil meine Benachrichtigungseinstellungen damals suboptimal waren. Ich bin auch erstaunt, wie häufig die Projektseite auf meiner Homepage aufgerufen wird. Ich lade morgen ein Bugfix hoch. Danke für den Hinweis!

**Comment by moewew** [comment]
Das mit den Benachrichtigungen kenne ich. Vielen Dank für das Update.

**Comment by CarlOrff** [comment]
Bugfix an CTAN versandt.
